### ISSUE TITLE
Pairing error

### ISSUE THREAD

**Issue by AkashKrx** [ttsudipto/smartIO#1]
I get incorrect pairing key error. The code is case sensitive and I'm sure I'm entering it right and it tells incorrect everytime

**Comment by AkashKrx** [comment]
Restarted both application and now Android app crashes after entering key

**Comment by AkashKrx** [comment]
Android log

`2018-10-22 00:54:08.411 26999-27040/project.android E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: project.android, PID: 26999
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at org.apache.commons.codec.binary.Base64.discardNonBase64(Base64.java:479)
        at org.apache.commons.codec.binary.Base64.decodeBase64(Base64.java:379)
        at project.android.security.EKEProvider.<init>(EKEProvider.java:134)
        at project.android.net.ConnectionTask.doInBackground(ConnectionTask.java:77)
        at project.android.net.ConnectionTask.doInBackground(ConnectionTask.java:43)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
2018-10-22 00:54:08.877 26999-26999/project.android E/WindowManager: android.view.WindowLeaked: Activity project.android.MainActivity has leaked window DecorView@3775e49[Connecting] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.app.Dialog.show(Dialog.java:329)
        at android.app.ProgressDialog.show(ProgressDialog.java:116)
        at android.app.ProgressDialog.show(ProgressDialog.java:104)
        at project.android.net.ConnectionTask.onPreExecute(ConnectionTask.java:60)
        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:620)
        at android.os.AsyncTask.execute(AsyncTask.java:567)
        at project.android.ConnectionFragment$3.onClick(ConnectionFragment.java:301)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22433)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
`

**Comment by montimaj** [comment]
I think the issue is with the write permission for storing the key at the PC end. Could you debug this function and check the password variable?
Line 116 [generateKSPassword()] of https://github.com/ttsudipto/smartIO/blob/master/src/project/pc/security/KeyStoreManager.java

**Comment by digital-idiot** [comment]
There are two possible reasons for this. In java8 windows, there is restriction on key size and strength. To bypass that you need to update the policy. Refer to this: https://www.andreafortuna.org/programming/java-tips-how-to-fix-the-invalidkeyexception-illegal-key-size-or-default-parameters-runtime/

Secondly, in windows the keystore is stored in registry by convention. This may cause permission issues. If you have mac or preferably linux, kindly try there once and see if this is reproducible in those environments.
